name: Build and deploy to gh-pages branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Checkout emsdk
        uses: actions/checkout@v4.1.1
        with:
          repository: emscripten-core/emsdk
          path: .emsdk

      - name: Cache emsdk installation
        id: cache-emsdk
        uses: actions/cache@v3
        with:
          path: .emsdk
          key: emsdk

      - name: Install emsdk
        if: steps.cache-emsdk.outputs.cache-hit != 'true'
        run: .emsdk/emsdk install 3.1.37

      - name: Activate emsdk
        run: .emsdk/emsdk activate 3.1.37

      - name: Cache QT installation
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: .qt
          key: qt

      - name: Install QT
        if: steps.cache-qt.outputs.cache-hit != 'true'
        run: python -m aqt install-qt linux desktop 6.6.0 wasm_singlethread --autodesktop -O .qt

      - name: Create Build System
        run: |
          source .emsdk/emsdk_env.sh
          bash .qt/6.6.0/wasm_singlethread/bin/qt-cmake -G "Unix Makefiles" -B .build -S . -DQT_HOST_PATH=".qt/6.6.0/gcc_64" -DCMAKE_PREFIX_PATH=".qt/6.6.0/wasm_singlethread"

      - name: Build Application
        run: cmake --build .build -v

      - name: Deploy
        uses: s0/git-publish-subdir-action@v2.6.0
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: .build/app
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3