name: Build qt-wasm and store build output in new branch

on:
  push:
    branches:
      - main
      - action_dev

permissions:
  deployments: write
  pages: write

env:
  VERSION: test

jobs:
  emsdk:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Emscripten
        uses: actions/checkout@v3
        with:
          repository: emscripten-core/emsdk
          path: emsdk
      - run: ./emsdk/emsdk install 2.0.14
      - run: ./emsdk/emsdk activate 2.0.14
      # - run: source emsdk/emsdk_env.sh
      # - run: em++ --version

  qt6:
    runs-on: ubuntu-20.04
    steps:
      - name: Install QT6
        uses: actions/checkout@v3
        with:
          repository: qt/qt5
          ref: v6.2.4
          path: qt6
      - run: perl qt6/init-repository --module-subset=qtbase
      # - run: mkdir qt6-build
      - run: ./qt6/configure -prefix $PWD/qtbase
      - run: cmake --build .

  deploy:
    needs: [emsdk, qt6]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3





